add features from Spring Data JPA
padu12/online-book-store pull request #3
Opened 2023-08-18 20:38 UTC by padu12

[link to the requirements](https://mate.academy/learn/java-spring-boot/java-spring-boot-data-jpa-v2?section=practice&videoId=5574&testTaskSlug=java_spring_boot_data_jpa)

2023-08-19 17:43 UTC, satori11111 approved these changes
Incredible! Shocking how you managed to do search in one class

2023-08-22 11:13 UTC, andrii-hoienko requested changes
Nice, but have some question

2023-08-22 11:13 UTC, andrii-hoienko commented on src/main/java/com/kaziamyr/onlinebookstore/specification/SpecificationProvider.java
> +    public Specification<Book> getSpecification(List<String> params, String fieldName) {
Is it possible to make specification provider generic?

2023-08-22 13:36 UTC, Vasul-Pankiv approved these changes

2023-08-22 14:09 UTC, vovasalyha approved these changes

2023-09-05 05:05 UTC, boroda4436 commented on pom.xml
> +<!--        <liquibase.version>4.22.0</liquibase.version>-->
You should not push commented code

2023-09-05 05:05 UTC, boroda4436 commented on pom.xml
> +            <version>4.22.0</version>
Why you are not using `liquibase.version` property here?

2023-09-05 05:05 UTC, boroda4436 commented on src/main/java/com/kaziamyr/onlinebookstore/controller/BookController.java
> +    public BookDto updateById(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
could be just `update`
```suggestion
    public BookDto update(@PathVariable Long id, @RequestBody CreateBookRequestDto bookDto) {
```

2023-09-05 05:05 UTC, boroda4436 commented on src/main/java/com/kaziamyr/onlinebookstore/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id = ?")
```

2023-09-05 05:05 UTC, boroda4436 commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-alter-books-table.yaml
changeset file name should describe what changes were applied. The `02-alter-books-table` is too generic

2023-09-06 15:05 UTC, merged