add validation and CustomGlobalExceptionHandler
padu12/online-book-store pull request #5
Opened 2023-08-19 10:53 UTC by padu12

2023-08-20 08:30 UTC, satori11111 requested changes
Great, please look at comments and add improvements

2023-08-20 08:30 UTC, satori11111 commented on src/main/java/com/kaziamyr/onlinebookstore/dto/CreateBookRequestDto.java
>      private String isbn;
isbn field has rules to check if it is valid, please create your custom annotation and validator or use annotation "@ISBN" that in org.hibernate.validator.constraints.ISBN

2023-08-20 08:30 UTC, satori11111 commented on src/main/java/com/kaziamyr/onlinebookstore/dto/CreateBookRequestDto.java
>      private BigDecimal price;
price cannot be less than zero, check it

2023-08-21 16:03 UTC, vovasalyha approved these changes

2023-08-21 16:03 UTC, vovasalyha commented on src/main/java/com/kaziamyr/onlinebookstore/dto/CreateBookRequestDto.java
>      private String title;
Most likely, you have some restriction on length of title and author in the database, so put according validation for length. Also you can set some meaningful minimum length, but it's for you to decide, maybe there can be some book with one symbol name, but not empty for sure.

2023-09-06 15:10 UTC, merged