Add category model
padu12/online-book-store pull request #8
Opened 2023-09-03 13:57 UTC by padu12

2023-09-08 07:52 UTC, boroda4436 commented on src/main/java/com/kaziamyr/onlinebookstore/repository/CategoryRepository.java
> +    Category getCategoryById(Long id);
we have default method `getReferenceById`

2023-09-11 13:54 UTC, andrii-hoienko requested changes
Nice, some minor improvements required

2023-09-11 13:54 UTC, andrii-hoienko commented on src/main/java/com/kaziamyr/onlinebookstore/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid SaveCategoryRequestDto request) {
```suggestion
    public CategoryDto create(@RequestBody @Valid SaveCategoryRequestDto request) {
```

2023-09-11 13:54 UTC, andrii-hoienko commented on src/main/java/com/kaziamyr/onlinebookstore/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid SaveCategoryRequestDto request) {
It is clear that you work with category here, not necessary to add it

2023-09-11 13:54 UTC, andrii-hoienko commented on src/main/java/com/kaziamyr/onlinebookstore/service/impl/BookServiceImpl.java
> +                Stream.of(requestDto.getCategoryIds())
move to separate method

2023-09-12 12:56 UTC, andrii-hoienko approved these changes

2023-09-12 13:24 UTC, merged